# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VK App New' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VK App New
  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'Kingfisher', '~> 5.12.0'
  pod 'SwiftyJSON', '~> 5.0.0'
  pod 'Realm', '~> 4.3.0'
  pod 'RealmSwift', '~> 4.3.0'

end
